---
- name: Install kafka (which includes zookeeper) from confluent repository
  apt: name=confluent-kafka-2.11 state=present
- name: Ensure log directory exists with correct permissions
  file:
    state: directory
    path: /var/log/kafka
    owner: data
    group: data
    mode: 0755
- name: Install Zookeeper Service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Start Zookeeper
- name: Copy Zookeeper config
  template:
    src: zookeeper.properties.j2
    dest: /etc/kafka/zookeeper.properties
    owner: data
    group: data
    mode: 0755
  notify:
    - Restart Zookeeper
