---
- hosts: all
  sudo: true
  gather_facts: no
  pre_tasks:
    - name: Install python2
      raw: sudo apt-get -y install python-simplejson
    - name: Gather facts
      setup:
    - include: tasks/packages.yml
  tasks:
    - include: tasks/kafka.yml
    - include: tasks/schema-registry.yml
