---
- hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: Install python2
      raw: sudo apt-get -y install python-simplejson
    - name: Gather facts
      setup:
  roles:
    - confluent-repo
    - java-8-jdk
    - riemann-tools
    - zookeeper
