---
- name: Add confluent apt key
  apt_key: url=http://packages.confluent.io/deb/3.0/archive.key state=present

- name: Add confluent repository
  apt_repository: repo='deb [arch=amd64] http://packages.confluent.io/deb/3.0 stable main' state=present

- name: Update apt cache
  apt: update_cache=yes

- name: Install Java Runtime Environment
  apt: name=openjdk-8-jre state=present
